apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-discord-proxy
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'discord'
      routes:
      - match:
          severity: warning
        receiver: 'discord'
    receivers:
    - name: 'discord'
      webhook_configs:
      - url: 'http://prometheus-discord:9094/alertmanager'
        send_resolved: true
type: Opaque
