apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prometheus-kube-prometheus-alertmanager
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'discord'
      routes:
      - match:
          severity: warning
        receiver: 'discord'
    receivers:
    - name: 'discord'
      webhook_configs:
      - url: 'https://discord.com/api/webhooks/1373711717019680879/1nWgfM6RxL_eDuCdHvx9ZDv7t5lIOQq6pi1gJcubaZqMJ88tctE1DRLdgBQNa5TU3RYM'
        send_resolved: true
type: Opaque
