prometheus:
  prometheusSpec:
    retention: 15d
    resources:
      requests:
        memory: 400Mi
        cpu: 300m
      limits:
        memory: 800Mi
        cpu: 500m
    additionalScrapeConfigs:
      - job_name: 'bestrong-api'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: bestrong-api
            action: keep
    ruleSelector:
      matchLabels:
        release: prometheus

grafana:
  enabled: true
  # adminPassword will be passed via --set
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "selfsigned-issuer"
    hosts:
      - "grafana.172.201.178.188.nip.io"
    tls:
      - secretName: grafana-tls
        hosts:
          - "grafana.172.201.178.188.nip.io"

alertmanager:
  enabled: true
  config: {}  # Empty config because we'll use a Secret instead
